baseURL = "http://cantillon.alhur.es:1313/"
languageCode = "en-us"
title = "Classless Base"
theme = "classless"

[params]
  show_summaries = true
  description = "Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Eu feugiat pretium nibh ipsum. Adipiscing vitae proin sagittis nisl."
